// TODO: Implement dark mode.
// TODO: Implement background images.
import "./globals.scss";

import { Providers } from "@/app/providers";
import { Cairo } from "next/font/google";
import Sidebar from "@/components/sidebar/Sidebar";
import NavBar from "@/components/navbar/NavBar";

const cairo = Cairo({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Alien Fish Digital Consulting",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1, shrink-to-fit=no",
  keywords: ["Web Application Development", "Digital Consulting"],
  authors: [
    { name: "Terry Lee Allen, Jr.", url: "https://github.com/TerryLeeAllenJr" },
  ],
  creator: "Terry Lee Allen, Jr.",
  publisher: "Alien Fish Consulting",
  formatDetection: {
    email: false,
    address: false,
    telephone: true,
  },
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className="light scroll-smooth"
      dir="ltr"
      suppressHydrationWarning
    >
      <body
        data-layout-mode="light"
        data-sidebar-size="default"
        data-theme-layout="vertical"
        className={cairo.className}
      >
        <div className="flex h-screen antialiased text-gray-900 bg-gray-100 dark:bg-dark dark:text-light">
          <Providers>
            <Sidebar />

            <div className="flex flex-col flex-1 min-h-screen overflow-x-hidden overflow-y-auto">
              <NavBar />
              <main>
                <div className="flex justify-center h-full w-full p-4">
                  {children}
                </div>
              </main>
            </div>
          </Providers>
        </div>
      </body>
    </html>
  );
}
